name: MLflow Project CI - Diabetes Retraining & Docker Build

on:
  push:
    branches: [ main ]
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci_workflow.yaml'
  workflow_dispatch:

jobs:
  run-mlflow-project-and-build-docker: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12 

      - name: Create/Update Conda Environment from File
        run: conda env update --file MLProject/conda.yaml --name base


      - name: Set up MLflow environment variables
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }} 
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} 
          MLFLOW_TRACKING_URI: https://dagshub.com/Yona1201/msml-proyek-briliona.mlflow 
        run: |
          echo "Setting MLflow environment variables..."
          echo "DAGSHUB_USER_NAME=${DAGSHUB_USERNAME}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${DAGSHUB_USERNAME}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${DAGSHUB_TOKEN}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}" >> $GITHUB_ENV
          echo "Env vars set."

      - name: Run MLflow Project (Retraining)
        id: mlflow_run 
        shell: bash -l {0} 
        run: |
          # Dapatkan nama environment dari conda.yaml (jika ada) atau gunakan 'base'
          ENV_NAME=$(head -n 1 MLProject/conda.yaml | cut -d' ' -f2)
          if [ -z "$ENV_NAME" ]; then
            ENV_NAME=base # Fallback ke base jika nama tidak ditemukan
          fi
          echo "Activating Conda environment: $ENV_NAME"
          conda activate "$ENV_NAME" # Aktifkan environment

          echo "Running MLflow project..."
          # Jalankan MLflow dari root, target folder MLProject
          # Tangkap output untuk mendapatkan Run ID
          mlflow run ./MLProject -e main > mlflow_run_output.txt
          cat mlflow_run_output.txt # Tampilkan output log
          
          # Ambil Run ID (baris terakhir output modelling.py)
          RUN_ID=$(grep 'Retraining Run ID:' mlflow_run_output.txt | awk '{print $NF}')
          if [ -z "$RUN_ID" ]; then
            echo "::warning::Could not extract MLflow Run ID using grep. Trying tail..."
            RUN_ID=$(tail -n 1 mlflow_run_output.txt | awk '{print $NF}') # Coba ambil baris terakhir
             if [[ ! "$RUN_ID" =~ ^[a-f0-9]{32}$ ]]; then # Validasi sederhana Run ID
               echo "::error::Extracted RUN_ID '$RUN_ID' does not look valid."
               # Coba cari di log lengkap
               RUN_ID=$(grep -o '[a-f0-9]\{32\}' mlflow_run_output.txt | tail -n 1)
               if [[ ! "$RUN_ID" =~ ^[a-f0-9]{32}$ ]]; then
                  echo "::error::Could not find a valid MLflow Run ID in the output."
                  exit 1
               fi
             fi
          fi
          echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Detected Retraining Run ID: $RUN_ID"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with MLflow
        env:
           MLFLOW_TRACKING_URI: https://dagshub.com/Yona1201/msml-proyek-briliona.mlflow 
           MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
           MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
           MLFLOW_RUN_ID_FROM_STEP: ${{ env.MLFLOW_RUN_ID }} 
        run: |
          echo "Building Docker image for MLflow Run ID: ${MLFLOW_RUN_ID_FROM_STEP}"
          # Ganti DOCKERHUB_USERNAME/IMAGE_NAME:TAG 
          # Contoh: yona1201/diabetes-model:latest
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/diabetes-msml-proyek:latest" # Ganti 'diabetes-msml-proyek' jika mau
          # URI model adalah runs:/<RUN_ID>/model
          MODEL_URI="runs:/${MLFLOW_RUN_ID_FROM_STEP}/model"
          echo "Using Model URI: ${MODEL_URI}"
          # --enable-mlserver penting untuk Kriteria 4
          mlflow models build-docker --model-uri "${MODEL_URI}" --name "${IMAGE_NAME}" --enable-mlserver 
          echo "DOCKER_IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Push Docker Image
        run: |
          echo "Pushing image: ${{ env.DOCKER_IMAGE_NAME }}"
          docker push ${{ env.DOCKER_IMAGE_NAME }}